language: java

services:
  - docker

 script:
  - ./mvnw clean install -Ptest
  - ./mvnw clean install -Pprod
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - ./mvnw dockerfile:build
  - if: branch = master ./mvnw dockerfile:push





