spring:
  application:
    name: atendimento
  data:
    mongodb:
      database: atendimento
      host: localhost
      port: 27017
      repositories:
        enabled: true

logging:
  level:
    root: info

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
    enabled: true
    healthcheck:
      enabled: true
  instance:
    appname: atendimento
    instanceId: atendimento:${spring.application.instance-id:${random.value}}
    metadata-map:
      profile: ${spring.profiles.active}
      version: ${project.version}
    ip-address: true





