version: '2'
services:
  postgres:
    image: postgres
    container_name: srv-postgres
    ports:
     - "5432:5432"
    environment:
         POSTGRES_PASSWORD: postgres
    volumes:
      - /home/periclesalmeida/repositorio/volumes/postgres/backup:/volume
      - /home/periclesalmeida/repositorio/volumes/postgres/data:/var/lib/postgresql/data


