version: '2'
services:
  mongo:
    image: mongo
    container_name: srv-mongo
    ports:
      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - $HOME/repositorio/volumes/mongo/data:/data/db
      - $HOME/repositorio/volumes/mongo/backup:/data/bkp
